### ISSUE TITLE
error decoding users when sending POST to endpoint

### ISSUE THREAD

**Issue by FloWi** [wi101/zio-examples#2]
Hi!

I get this error when posting to the users endpoint.
Do you have an idea what's wrong?

I didn't run it with a todo-app frontend and just tried to post manually using cURL or httpie.

```bash
$ curl -XPOST localhost:8080/users -d '{"id": 1, "name": "Florian"}'
$ http POST localhost:8080/users id=1 name=Florian
```
[stacktrace.log](https://github.com/wi101/zio-examples/files/4236555/stacktrace.log)

**Comment by wi101** [comment]
Thanks!
```
An unchecked error was produced.
java.lang.NoClassDefFoundError: io/circe/ObjectEncoder
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
```
I upgrade the circe version and it fixes this issue
